# Generated by Django 5.2 on 2025-04-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_filme_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='genero',
            field=models.CharField(choices=[('acao', 'Ação'), ('comedia', 'Comédia'), ('drama', 'Drama'), ('terror', 'Terror'), ('ficcao', 'Ficção Científica')], default='drama', max_length=20),
        ),
    ]
